### PR TITLE
ikurtz-cloudbees-ci-aws-quickstart-doc-edits

### PR DESCRIPTION
**Pull request by ikurtz**
*Issue #, if available:*

*Description of changes:*

Here is a list of the major changes to the deployment guide that I (ikurtz) have made:

1. Removal of Spot Integration as a default deployment option. CloudBees deemed the related resources unnecessary to get started with CI. This was done within several files ... namely within the CloudFormation templates for new/existing VPCs. However, I've kept a reference to the Spot integration within the deployment guide in sections that call it out. We did so in the event certain people wanted to include it as a third partition.
2. Transitioning from the efs-provisioner to EFS CSI Driver for storage
3. Removing all references to "Managed Master" and "Quick Start" (where we can) and replacing them with updated terminology such as "Managed Controllers" and "Partner Solution", respectively.
4. A brand new Architecture Diagram, denoting the Spot Agent partition as entirely optional
5. Updating the default instance type from r5.xlarge for the Controller Nodes partition to an m5.xlarge
6. Substituting obsolete and/or broken links with updated links

If there are _any_ questions or concerns with my repo structure, major/minor changes to the deployment guide, or anything else related to this effort... don't hesitate to let me know!

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by wellsiau-aws** [comment]
@ikurtz , as we discussed, please add the following fix:
1. relative link to the assets (picture, diagram)
2. change generic reference to "Partner Solutions" 
3. fix the note section

You can run local build by using
```
asciidoctor --base-dir docs/ --backend=html5 -o ../index.html -w --doctype=book -a toc2 -a production_build docs/boilerplate/index_deployment_guide.adoc && open index.html
```

**Comment by ikurtz** [comment]
@wellsiau-aws - I've just made a new commit to the `doc-edits` branch in my forked copy of the repo inclusive of all required fixes.

**Comment by schottsfired** [comment]
Thank you for doing this @ikurtz !

**Comment by ikurtz** [comment]
> Thank you for doing this @ikurtz !

@schottsfired My pleasure. Hope things are well with you my man, would love to catch up!

**Comment by wellsiau-aws** [comment]
local build runs successfully without any error / warnings
```
asciidoctor --base-dir docs/ --backend=html5 -o ../index.html -w --doctype=book -a toc2 -a production_build docs/boilerplate/index_deployment_guide.adoc && open index.html
```

visual inspection done, no typos or other rendering issues. LGTM

**Comment by wellsiau-aws** [comment]
this is ready to merge

**Pull request merged**
